# Generated by Django 5.0 on 2023-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMusician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('instrument_type', models.CharField(choices=[('guitar', 'Guitar'), ('Flute', 'Flute'), ('Tobla', 'Tobla'), ('Dhol', 'Dhol')], max_length=20)),
            ],
        ),
    ]
