# Generated by Django 5.0 on 2023-12-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addalbum',
            name='musician_email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musician.addmusician'),
        ),
    ]
