# Generated by Django 5.0 on 2023-12-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_addalbum_musician_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addalbum',
            old_name='musician_email',
            new_name='musician_name',
        ),
    ]
